from typing import overload
from languagemodels.config import Config

config: Config = ...

def chat(prompt: str) -> str: ...
@overload
def do(prompt: list[str]) -> list[str]: ...
@overload
def do(prompt: str) -> str: ...
